#!/usr/bin/env bash
set -ueo pipefail

# This script generates a version of the colour scheme for use in Sublime Merge.
# Why is this necessary when SM can use ST colour schemes as-is? Because I don't
# want full-on programming language syntax highlighting when looking at diffs in
# SM, and it's not currently possible to disable syntax highlighting in SM:
# https://github.com/sublimehq/sublime_merge/issues/52

ST_CS_PATH="Humid.sublime-color-scheme"
SM_CS_PATH="HumidSM.sublime-color-scheme"
SMDIFF_CS_PATH="HumidSMDiff.sublime-color-scheme"

# REF: https://unix.stackexchange.com/a/11306
# REF: https://stackoverflow.com/a/32569573/82

# REF: https://github.com/spyoungtech/json-five
# REF: https://github.com/hauntsaninja/pyp

cat <(sed -E '/^ +"rules":/q ; s/(^ +"name":).+/\1 "HumidSM",/' "${ST_CS_PATH}") \
	<(sed -E '1,/^ +\/\/ HumidSM allowlist starts here/ d' "${ST_CS_PATH}") |
	pyp 'cs = json5.load(stdin); cs["name"] = "HumidSM"; json.dumps(cs, indent=True)' \
		>"${SM_CS_PATH}"

pyp <"${SM_CS_PATH}" '
cs = json.load(stdin)
cs["name"] = "HumidSMDiff"
cs["globals"]["foreground"] = "color(var(white_faded) lightness(- 40%))"
json.dumps(cs, indent=True)' >"${SMDIFF_CS_PATH}"
