#!/usr/bin/env bash
set -ueo pipefail

# This script generates a version of the colour scheme for use in Sublime Merge.
# Why is this necessary when SM can use ST colour schemes as-is? Because I don't
# want full-on programming language syntax highlighting when looking at diffs in
# SM, and it's not currently possible to disable syntax highlighting in SM:
# https://github.com/sublimehq/sublime_merge/issues/52

ST_CS_PATH="Humid.sublime-color-scheme"
SM_CS_PATH="HumidSM.sublime-color-scheme"
SMDIFF_CS_PATH="HumidSMDiff.sublime-color-scheme"

# REF: https://unix.stackexchange.com/a/11306
# REF: https://stackoverflow.com/a/32569573/82

# @todo For stripping comments from the JSON, use something better than the fragile sed approach
# @body Is there a commandline JSON5-to-JSON converter?
# @body Or, use https://github.com/hauntsaninja/pyp instead of jello, and import the library https://github.com/spyoungtech/json-five ?

cat <(sed -E '/^ +"rules":/q ; s/(^ +"name":).+/\1 "HumidSM",/' "${ST_CS_PATH}") \
	<(sed -E '1,/^ +\/\/ HumidSM allowlist starts here/ d' "${ST_CS_PATH}") |
	sed -E 's/ \/\/.*$//' |
	jello '_.name = "HumidSM"; _' >"${SM_CS_PATH}"

jello <"${SM_CS_PATH}" '
_.name = "HumidSMDiff"
_.globals.foreground = "color(var(white_faded) lightness(- 40%))"
_' >"${SMDIFF_CS_PATH}"
